--- 
- name: Spring_boot_deployment
  hosts: appserver 
  become: yes
  vars:
    java_package: openjdk-11-jdk
    app_dir: /usr/share/springpetclinic
    download_url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
    app_file_name: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
    spring_user: springbootuser
    service_file_path: /etc/systemd/system/springpetclinic.service
  tasks:
    - name: Update ubuntu packages and install openjdk 11
      apt:
        name: {{ java_package }}
        update_cache: yes
        state: present 
    - name: Creating directory 
      file:
        path: {{ app_dir }}
        state: directory 
    - name: downloading spring_petclinic package
      get_url:
        url: {{ download_url }}
        dest: {{ app_file_name }}
    - name: Creating springboot user 
      user:
        name: {{ spring_user }}
        password: Pranju@1996
        state: present 
    - name: Changing ownership of jar file
      file:
        path: {{ app_file_name }}
        owner: {{ spring_user }}
        mode: '500'
        state: file
    - name: Copying Service file from local location 
      copy:
        src: springpetclinic.service
        dest: {{ service_file_path }}
    - name: Make sure spring petclinc service are running
      systemd:
        name: springpetclinic.service
        enabled: yes
        state: started 






