--- 
- name: Spring_boot_deployment
  hosts: appserver 
  become: yes
  tasks:
    - name: Update ubuntu packages and install openjdk 11
      apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present 
    - name: Creating directory 
      file:
        path: /usr/share/springpetclinic
        state: directory 
    - name: downloading spring_petclinic package
      get_url:
        url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
        dest: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
    - name: Creating springboot user 
      user:
        name: springbootuser
        password: Pranju@1996
        state: present 
    - name: Changing ownership of jar file
      file:
        path: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
        owner: springbootuser 
        mode: '500'
        state: file
    - name: Copying Service file from local location 
      copy:
        src: springpetclinic.service
        dest: /etc/systemd/system/springpetclinic.service
    - name: Make sure spring petclinc service are running
      systemd:
        enabled: yes
        state: started 






#  1  sudo apt update
#  2  sudo apt install openjdk-11-jdk -y
#  3  sudo mkdir /usr/share/springpetclinic
#  4  wget https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
#  5  sudo cp spring-petclinic-2.4.2.jar /usr/share/springpetclinic/
#  6  sudo adduser springbootuser
#  7  sudo chown springbootuser:springbootuser /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
#  8  sudo chmod 500 /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
#  9  sudo vi /etc/systemd/system/springpetclinic.service
# 10  sudo systemctl enable springpetclinic.service
# 11  sudo systemctl start springpetclinic.service
# 12  sudo systemctl status springpetclinic.service